# ----
# Site

title: Bogong Rover Chalet Information Hub
url: "https://info.bogongroverchalet.org.au/"
baseurl:
google_analytics_key: UA-70761518-3
disqus_shortname:
newsletter_action:

mainsite: http://preview.bogongroverchalet.org.au/

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Bogong Rover Chalet Information Hub
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Bogong Rover Chalet
  links:
    - https://bogongroverchalet.org.au/
    - https://info.bogongroverchalet.org.au/

# -----
# Build

permalink: /:categories/:title/

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  sets:


jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      comments: true
      type: Document
  -
    scope:
      type: "sets"
    values:
      _hide_content: true
  -
    scope:
      path: "index.html"
    values:
      body_class: "show_hero_search"
# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

types:
  - Document
  - Video

_comments:
